"""
Test Writer Agent for Amaze on Work.

Generates targeted pytest (Python) or Jest (Node.js) test cases
from the incident description, root cause, and proposed fix.

Tests are designed to:
  - FAIL on the original buggy code (reproducing the incident)
  - PASS after the fix is applied (confirming the patch works)
"""

import json
import logging
import re
from typing import Optional

from src.agents.base import BaseAgent, AgentResponse
from src.agents.state import PipelineState, AgentType
from src.llm.base_client import BaseLLMClient

logger = logging.getLogger(__name__)


class TestWriterAgent(BaseAgent):
    """
    Generates targeted test cases for incident validation.

    The tests are injected into the Docker sandbox alongside the fix
    to confirm the fix resolves the reported issue without regressions.
    """
    agent_type = AgentType.VALIDATION  # shares pipeline slot, called from ValidationAgent

    def execute(self, state: PipelineState) -> AgentResponse:
        incident = state.get("incident", {}) or {}
        root_cause = state.get("root_cause", {}) or {}
        fix_plan = state.get("fix_plan", {}) or {}
        language = state.get("language", "python")

        tests = self._generate_tests(incident, root_cause, fix_plan, language)

        return AgentResponse(
            success=bool(tests),
            message=f"Generated {len(tests)} test function(s) for validation",
            data={"generated_tests": tests, "language": language},
        )

    async def aexecute(self, state: PipelineState) -> AgentResponse:
        return self.execute(state)

    def generate(
        self,
        incident: dict,
        root_cause: dict,
        fix_plan: dict,
        language: str = "python",
    ) -> str:
        """
        Generate a complete test file string for the given incident + fix.

        Returns:
            str: A complete pytest or Jest test file content ready to write to disk.
                 Empty string if generation fails.
        """
        tests = self._generate_tests(incident, root_cause, fix_plan, language)
        if not tests:
            return ""
        return tests

    def _generate_tests(
        self,
        incident: dict,
        root_cause: dict,
        fix_plan: dict,
        language: str,
    ) -> str:
        """Core LLM call to generate test file content."""
        title = incident.get("title", "")
        error_log = incident.get("error_log", "") or incident.get("description", "")
        hypothesis = root_cause.get("hypothesis", "") or root_cause.get("root_cause_summary", "")
        suspect_files = root_cause.get("suspect_files", [])
        service = incident.get("affected_service", "")

        # Build changes summary for context
        changes = []
        for ch in fix_plan.get("files_to_modify", []):
            f = ch.get("file_path", "")
            orig = ch.get("original_code", "")[:300]
            fixed = ch.get("fixed_code", "")[:300]
            rationale = ch.get("rationale", "")
            if f:
                changes.append(
                    f"File: {f}\nRationale: {rationale}\n"
                    f"Before:\n```\n{orig}\n```\nAfter:\n```\n{fixed}\n```"
                )
        changes_text = "\n\n".join(changes) or "No specific file changes recorded."

        if language == "python":
            format_instructions = """
Write a complete pytest test file. CRITICAL RULES:
- The test file will be placed in `_amaze_tests/` (NOT in `tests/`), so imports must work from there
- Add `import sys, os; sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))` at the top
- Import only standard library + the service module being fixed (e.g., `from app.services.payment_service import calculate_tax`)
- DO NOT import from conftest.py, DO NOT import `create_app`, `db`, or Flask test fixtures
- DO NOT use any Flask test client — test pure Python functions directly
- Write 2-4 focused test functions that exercise the EXACT code path that was broken
- Each test must have a clear docstring explaining what it validates
- Tests should confirm the bug is FIXED (they should PASS after the fix)
- Add one test that confirms no regression in adjacent functionality
- Use `pytest.mark.parametrize` for boundary cases if appropriate
- File must be self-contained and runnable with: `pytest _amaze_tests/ -v`
- DO NOT mock the entire module — test real behavior
- Output ONLY valid Python code, no explanation text
"""
            file_header = "# Generated by Amaze on Work TestWriter\nimport sys\nimport os\nsys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))\nimport pytest\n"

        else:
            format_instructions = """
Write a complete Jest test file. Rules:
- Use `describe` blocks with clear names matching the bug scenario
- Write 2-4 focused `it()` / `test()` cases that exercise the broken code path
- Import only from the service module being fixed
- Tests should PASS after the fix is applied
- Include one regression guard test for adjacent features
- File runnable with: `npx jest test_Amaze on Work_generated.test.js`
- Output ONLY valid JavaScript/TypeScript, no explanation text
"""
            file_header = "// Generated by Amaze on Work TestWriter — DO NOT EDIT\n"

        prompt = f"""You are a Senior QA Engineer and Test Automation Specialist at a large SRE team.

=== INCIDENT ===
Title: {title}
Service: {service}
Error Log:
{error_log[:800]}

=== ROOT CAUSE ===
{hypothesis[:600]}

Suspect Files: {', '.join(suspect_files[:5]) or 'Unknown'}

=== FIX APPLIED ===
{changes_text[:1200]}

=== YOUR TASK ===
{format_instructions}

Generate a {'pytest' if language == 'python' else 'Jest'} test file that:
1. Verifies the ROOT CAUSE described above is now FIXED
2. Does NOT break any existing passing tests
3. Is minimal, targeted, and surgical — no test sprawl

{file_header}"""

        try:
            messages = [
                {
                    "role": "system",
                    "content": (
                        "You are a Senior QA Engineer specializing in test automation for incident validation. "
                        "You write precise, minimal test cases that confirm bug fixes without over-testing."
                    ),
                },
                {"role": "user", "content": prompt},
            ]
            response = self.llm.complete(messages)
            content = response.content if hasattr(response, "content") else str(response)

            # Extract code block if wrapped in markdown
            code_match = re.search(r"```(?:python|javascript|typescript|js|ts)?\n(.*?)```", content, re.DOTALL)
            if code_match:
                return code_match.group(1).strip()

            # If no code block, return the whole response if it looks like code
            if "def test_" in content or "it(" in content or "test(" in content:
                return content.strip()

            logger.warning("[TestWriter] LLM response did not contain recognizable test code")
            return ""

        except Exception as e:
            logger.error(f"[TestWriter] Test generation failed: {e}")
            return ""

    def get_system_prompt(self) -> str:
        return (
            "You are the Test Writer Agent in Amaze on Work. "
            "You generate targeted pytest or Jest test cases to validate that "
            "the proposed fix resolves the reported incident."
        )
